using System;
using System.Collections.Generic;
using System.Linq;
using MusicTracker.Engine.Flow;        // PatternGenerator
using MusicTracker.Engine.Timeline;    // RiffNote
using MusicTracker.Engine.ComposerV2;  // CorpusModelV2, MusicMathV2

namespace MusicTracker.Engine.ComposerV3
{
    /// <summary>
    /// MATHÉMATIQUE — a model-FREE composer: the melodic CONTOUR comes from a formula / fractal (the Style), then it is
    /// made musical by FITTING each note to the present chord (chord tone on strong beats &amp; chord onsets) and
    /// VOICE-LEADING across chord changes (the new chord is entered from the nearest chord tone to the previous note, and
    /// leaps are capped to a fifth — no violent jumps). The RHYTHM is also formula-chosen but quantized to a clean,
    /// reused motif (balanced, never messy). Chords + accompaniment are generated by simple theory (no learned model).
    /// </summary>
    public sealed class MathComposerV3 : BaseComposerV3
    {
        // The math SOURCE is chosen via the Style list (like prélude/fugue for Bach).
        public override IReadOnlyList<string> Styles =>
            new[] { "Fractale chaotique", "Nombre d'or", "Ondes (sinus)", "Marche fractale 1/f" };

        // diatonic triad qualities by scale degree (PatternGenerator index: 0=maj, 1=min, 2=dim)
        static readonly int[] MajTriad = { 0, 1, 1, 0, 0, 1, 2 };
        static readonly int[] MinTriad = { 1, 2, 0, 1, 1, 0, 0 };

        // ============ CHORDS — simple functional progression (no learned model) ============
        public override List<(int rootPc, int quality)> GetChords(EmitContext ctx, SectionContext sec, int measureCount, int chordsPerMeasure)
        {
            int tonic = Mod12(ctx.TonicPc);
            int[] sc = ctx.Scale ?? (ctx.Minor ? MusicMathV2.MinorScale : MusicMathV2.MajorScale);
            int[] qual = ctx.Minor ? MinTriad : MajTriad;
            // a pleasing functional pattern per section role (scale-degree indices 0..6)
            int[] pat;
            switch (sec.Role)
            {
                case "intro": pat = new[] { 0, 4 }; break;                 // I – V
                case "outro": pat = new[] { 3, 4, 0, 0 }; break;           // IV – V – I – I (cadence)
                default: pat = ctx.Minor ? new[] { 0, 5, 2, 4 } : new[] { 0, 4, 5, 3 }; break; // i-VI-III-v  /  I-V-vi-IV
            }
            var outl = new List<(int, int)>();
            int bars = Math.Max(1, measureCount);
            for (int b = 0; b < bars; b++)
            {
                int deg = pat[b % pat.Length] % 7;
                int rootPc = Mod12(tonic + sc[Math.Min(sc.Length - 1, deg)]);
                outl.Add((rootPc, qual[deg]));
            }
            return outl;
        }

        // ============ NOTES — formula contour, chord-fitted + voice-led ============
        public override List<RiffNote> GetNote(EmitContext ctx, SectionContext sec, Staff staff, List<(int rootPc, int quality)> chords, int measureCount, List<RiffNote> themeNotes)
        {
            var outl = new List<RiffNote>();
            if (chords == null || chords.Count == 0) return outl;
            int tonic = Mod12(ctx.TonicPc);
            int[] sc = ctx.Scale ?? (ctx.Minor ? MusicMathV2.MinorScale : MusicMathV2.MajorScale);
            int lo = staff == Staff.Counter ? loCnt : loMel;
            int hi = staff == Staff.Counter ? hiCnt : hiMel;
            int bars = Math.Max(1, measureCount);
            var rng2 = new Random(ctx.Seed ^ StyleSeed(ctx.Style) ^ (staff == Staff.Counter ? 1234567 : 0));

            // the math contour: a long-enough sequence of values in [0,1)
            var seq = MathSequence(ctx.Style, bars * 16 + 32, rng2);
            int si = 0;

            // the BASE motif palette (varied 1-beat cells) — continuous sixteenths are reserved for the ÉLAN, so the
            // momentum burst contrasts with the motif instead of blurring into it.
            string[] palette = { "q", "8+8", "8.+16", "16+8.", "16+16+8", "8+16+16" };

            int cur = 60 + tonic; while (cur < lo) cur += 12; while (cur > hi) cur -= 12; cur = SnapScale(cur, tonic, sc);
            int phraseBars = (bars % 4 == 0) ? 4 : ((bars % 2 == 0) ? 2 : 1);
            int nPhrases = Math.Max(1, bars / phraseBars);

            // ANCHORS: the formula gives ONE structural note per beat — a chord tone, voice-led from the previous anchor
            // (leap-capped). The rhythm's in-beat subdivisions then FILL between anchors with stepwise PASSING TONES, so the
            // line is conjunct and singing rather than a jumpy note-per-formula-value.
            int nBeatsTotal = Math.Max(1, bars * 4);
            var anchor = new int[nBeatsTotal];
            int aPrev = cur;
            for (int beat = 0; beat < nBeatsTotal; beat++)
            {
                var ch = chords[Math.Min(chords.Count - 1, beat / 4)];
                int[] cp = ChordToneClasses(ch.rootPc, ch.quality, tonic);
                double v = seq[si % seq.Count]; si++;
                int target = SnapScale(lo + (int)Math.Floor(v * (hi - lo + 1)), tonic, sc);
                bool chordChange = (beat % 4 == 0) && beat > 0;
                int d = chordChange ? NearestChordTone(aPrev + Math.Sign(target - aPrev) * 2, cp, tonic) : NearestChordTone(target, cp, tonic);
                if (Math.Abs(d - aPrev) > 7) { int dir0 = Math.Sign(d - aPrev); d = NearestChordTone(aPrev + dir0 * 7, cp, tonic); }
                while (d > hi) d -= 12; while (d < lo) d += 12;
                anchor[beat] = d; aPrev = d;
            }
            cur = anchor[0];

            for (int ph = 0; ph < nPhrases; ph++)
            {
                int phraseAbs = ph * phraseBars * Bar;
                bool lastPhrase = ph == nPhrases - 1;
                foreach (var slot in BuildPhraseRhythm(phraseBars, lastPhrase, seq, ref si, palette))
                {
                    int absPos = phraseAbs + slot[0], dur = slot[1];
                    if (slot[2] == 1) continue;                                  // a deliberate breath (soupir) — leave the gap
                    int beat = Math.Min(nBeatsTotal - 1, absPos / Beat);
                    int pitch;
                    if (absPos % Beat == 0)
                        pitch = anchor[beat];                                    // first note of the beat = the formula anchor (chord tone)
                    else
                    {
                        int nextA = anchor[Math.Min(nBeatsTotal - 1, beat + 1)]; // FILL: step toward the next anchor (passing tone)
                        int dir = Math.Sign(nextA - cur);
                        if (dir == 0) pitch = ScaleStepDir(cur, ((absPos / 6) % 2 == 0) ? 1 : -1, tonic, sc);   // neighbour when already arrived
                        else { pitch = ScaleStepDir(cur, dir, tonic, sc); if ((nextA - cur) * (nextA - pitch) < 0) pitch = nextA; }   // no overshoot
                        while (pitch > hi) pitch -= 12; while (pitch < lo) pitch += 12;
                    }
                    outl.Add(new RiffNote(Math.Max(0, Math.Min(95, pitch - 12)), absPos, Math.Max(1, dur)));
                    cur = pitch;
                }
            }
            outl.Sort((a, c) => a.Start.CompareTo(c.Start));
            return outl;
        }

        // Build ONE phrase's rhythm as a real PHRASE (not a repeated ostinato): state a motif, gather momentum (ÉLAN —
        // busier subdivisions) toward a golden-section peak, LAND on a longer cadential note, then BREATHE — a soupir at
        // the start of the last beat, sometimes resolved by an ANACRUSE pickup into the next phrase. The motif + the
        // élan/breath choices are math-driven and VARY per phrase, so successive phrases differ. Slots = {start,dur,isRest}.
        List<int[]> BuildPhraseRhythm(int phraseBars, bool lastPhrase, List<double> seq, ref int si, string[] palette)
        {
            var slots = new List<int[]>();
            int nBeats = Math.Max(2, phraseBars * 4);
            // a TWO-cell rhythmic motif (A then B, distinct) alternated beat-by-beat → a 2-beat idea that's varied,
            // not a single cell looped. A/B are chosen from the palette (math-driven) and vary per phrase.
            int ia = PickIdx(seq, ref si, palette.Length);
            int ib = PickIdx(seq, ref si, palette.Length); if (ib == ia) ib = (ia + 1 + PickIdx(seq, ref si, palette.Length - 1)) % palette.Length;
            string cellA = palette[ia], cellB = palette[ib];
            const string busy = "16+16+16+16";
            int peak = Math.Max(1, (int)Math.Round(0.62 * nBeats));      // the "montée" target
            bool anacrusis = !lastPhrase && seq[si++ % seq.Count] < 0.5; // sometimes a pickup into the next phrase
            // the two motif cells are deployed in a RANDOM GROUPING (not strict A-B) — gives an irregular, lively motif
            string[] groups = { "AA", "BB", "AB", "BA", "ABA", "BAB", "AAB", "BBA", "ABB", "BAA" };
            string group = groups[PickIdx(seq, ref si, groups.Length)];
            int gi = 0;

            for (int beat = 0; beat < nBeats; beat++)
            {
                int bs = beat * Beat;
                if (nBeats >= 4 && beat == nBeats - 3)
                {
                    slots.Add(new[] { bs, 2 * Beat, 0 });                // LANDING: a long held note (half) over 2 beats
                    beat++;                                              // consumed the penultimate beat too
                }
                else if (beat == nBeats - 1)
                {
                    slots.Add(new[] { bs, Beat / 2, 1 });                // SOUPIR at the start of the last beat (fin de mesure)
                    slots.Add(new[] { bs + Beat / 2, Beat / 2, anacrusis ? 0 : 1 });   // anacruse pickup, or breathe on
                }
                else if (beat == peak - 1 || beat == peak)
                {
                    int pos = bs; foreach (var tok in busy.Split('+')) { int d = DurOf(tok); slots.Add(new[] { pos, d, 0 }); pos += d; }   // ÉLAN
                }
                else if (beat + 2 <= peak - 1 && seq[si++ % seq.Count] < 0.18)
                {
                    // SYNCOPE: "8 q 8" over two beats — the middle quarter starts off-beat and straddles the beat boundary
                    slots.Add(new[] { bs, Beat / 2, 0 });
                    slots.Add(new[] { bs + Beat / 2, Beat, 0 });
                    slots.Add(new[] { bs + Beat / 2 + Beat, Beat / 2, 0 });
                    beat++;                                              // consumed two beats
                }
                else
                {
                    string cell = (group[gi % group.Length] == 'A') ? cellA : cellB;   // deploy the grouping pattern
                    gi++;
                    int pos = bs; foreach (var tok in cell.Split('+')) { int d = DurOf(tok); slots.Add(new[] { pos, d, 0 }); pos += d; }
                }
            }
            return slots;
        }

        // chord pitch-classes RELATIVE to the tonic (what NearestChordTone expects: it does Mod12(tonicPc + cpc))
        static int[] ChordToneClasses(int rootPc, int quality, int tonicPc)
        {
            var notes = PatternGenerator.ChordNotes(((rootPc % 12) + 12) % 12, 0, quality, 0);
            return notes.Select(n => Mod12(n - tonicPc)).Distinct().ToArray();
        }

        static int DurOf(string tok)
        {
            switch (tok) { case "16": return 6; case "8": return 12; case "8.": return 18; case "q": return 24; case "q.": return 36; case "h": return 48; default: return 12; }
        }

        static int PickIdx(List<double> seq, ref int si, int mod)
        {
            double v = seq[si % seq.Count]; si++;
            int i = (int)Math.Floor(v * mod); if (i < 0) i = 0; if (i >= mod) i = mod - 1;
            return i;
        }

        static int StyleSeed(string style)
        {
            if (string.IsNullOrEmpty(style)) return 0;
            int h = 17; foreach (char c in style) h = h * 31 + c; return h;
        }

        // The math CONTOUR: a sequence of values in [0,1) — the Style picks the formula/fractal.
        static List<double> MathSequence(string style, int count, Random rng)
        {
            var s = new List<double>(count);
            string st = (style ?? "").ToLowerInvariant();
            if (st.Contains("or") || st.Contains("fibo"))
            {
                const double phi = 0.61803398874989; double a = rng.NextDouble();
                for (int i = 0; i < count; i++) { a += phi; s.Add(a - Math.Floor(a)); }   // golden low-discrepancy spread
            }
            else if (st.Contains("onde") || st.Contains("sin"))
            {
                double ph = rng.NextDouble() * 6.283;
                for (int i = 0; i < count; i++) { double y = Math.Sin(i * 0.7 + ph) + 0.5 * Math.Sin(i * 1.3 + 1.0); s.Add((y + 1.5) / 3.0); }
            }
            else if (st.Contains("marche") || st.Contains("1/f") || st.Contains("brown") || st.Contains("fractale 1"))
            {
                double x = 0.5;                                                            // bounded smoothed random walk (1/f-ish)
                for (int i = 0; i < count; i++) { x += (rng.NextDouble() - 0.5) * 0.34; if (x < 0) x = -x; if (x > 1) x = 2 - x; s.Add(Math.Max(0, Math.Min(0.999, x))); }
            }
            else
            {
                double x = 0.35 + 0.3 * rng.NextDouble(); const double r = 3.83;           // logistic map (controlled chaos)
                for (int i = 0; i < count; i++) { x = r * x * (1 - x); s.Add(Math.Max(0, Math.Min(0.999, x))); }
            }
            return s;
        }
    }
}
