using System;
using System.Collections.Generic;
using System.Linq;

namespace MusicTracker.Engine.Compose
{
    /// <summary>
    /// 100 % PROCEDURAL theme generator — no learned corpus, no network. Each technique is an algorithm from Gerhard
    /// Nierhaus, <i>Algorithmic Composition</i> (see docs/algorithmic-composition-nierhaus.md): twelve-tone SERIALISM,
    /// elementary CELLULAR AUTOMATA (Wolfram/Beyls), L-SYSTEMS (Lindenmayer/DuBois), GENETIC search with the Towsey
    /// objective fitness, 1/f FRACTAL noise (Voss-McCartney) and the self-similar THUE-MORSE morphism.
    ///
    /// RHYTHM is decoupled from pitch and generated by a SHARED, METER-AWARE layer (<see cref="GenerateRhythm"/>): the
    /// beat is always 24 slices; a BINARY meter subdivides it by 2/4 (durations 6/12), a TERNARY (compound x/8) meter by
    /// 3/6 (durations 4/8); notes group by whole beats (24/48/72/96) and never start mid-beat, for balanced rhythm.
    /// Each technique only supplies the PITCH stream; the rhythm is the same, correct one regardless of the algorithm.
    /// Output is in the app's units: <see cref="RiffNote"/> (Note = MIDI − 12) at 24 slices/quarter.
    /// </summary>
    public static class ProceduralComposer
    {
        public enum ProcTechnique { Serial, CellularAutomaton, LSystem, Genetic, Fractal1f, ThueMorse }

        public sealed class ProcResult
        {
            /// <summary>Melody in timeline units (Note = MIDI − 12, spq 24), length = bars × barSlices.</summary>
            public List<RiffNote> Melody = new List<RiffNote>();
            /// <summary>Verticalized block-chord accompaniment (used out-of-structure when no chord track exists).</summary>
            public List<RiffNote> ChordAccomp = new List<RiffNote>();
            /// <summary>Serial pitch row (info/debug).</summary>
            public int[] PitchRow;
        }

        const int Beat = 24;                 // one temps = 24 slices (always)
        const int REST = int.MinValue;       // pitch sentinel = a rest slot

        /// <summary>
        /// Generate a theme (+ optional verticalized accompaniment) with the chosen technique.
        /// <paramref name="barSlices"/> = slices per bar (<c>RulerBeatsPerBar()×24</c>, or the arrangement's <c>BarSlices</c>).
        /// <paramref name="ternary"/> = compound meter (x/8): the beat divides in 3/6 instead of 2/4.
        /// <paramref name="scale"/> = semitone offsets from the tonic; ignored (chromatic) for serial when
        /// <paramref name="chromatic"/> is true. <paramref name="harmonyDegrees"/> (one (rootPc,quality) per bar) biases
        /// the tonal techniques toward chord tones; null = free.
        /// </summary>
        public static ProcResult Generate(ProcTechnique tech, int bars, int barSlices, bool ternary,
            int tonicPc, int[] scale, bool chromatic, int seed, int loNote = 60, int hiNote = 84,
            List<(int rootPc, int quality)> harmonyDegrees = null)
        {
            bars = Math.Max(1, bars);
            if (scale == null || scale.Length == 0) scale = new[] { 0, 2, 4, 5, 7, 9, 11 };
            if (barSlices < Beat) barSlices = 4 * Beat;
            int total = bars * barSlices;
            var rng = new Random(seed);
            tonicPc = Mod(tonicPc, 12);

            var rhythm = MeterRhythm.GenerateRhythm(total, barSlices, ternary, rng);
            int count = rhythm.Count;

            var res = new ProcResult();
            List<int> pitches;
            switch (tech)
            {
                case ProcTechnique.Serial: pitches = SerialPitches(res, count, tonicPc, rng, loNote, hiNote); break;
                case ProcTechnique.CellularAutomaton: pitches = CaPitches(count, tonicPc, scale, chromatic, rng, loNote, hiNote); break;
                case ProcTechnique.LSystem: pitches = LSystemPitches(tonicPc, scale, rng, loNote, hiNote); break;
                case ProcTechnique.Genetic: pitches = GeneticPitches(count, tonicPc, scale, rng, loNote, hiNote, harmonyDegrees, rhythm, barSlices); break;
                case ProcTechnique.Fractal1f: pitches = FractalPitches(count, tonicPc, scale, rng, loNote, hiNote); break;
                default: pitches = ThueMorsePitches(count, tonicPc, scale, rng, loNote, hiNote); break;
            }
            Assemble(res, rhythm, pitches);

            res.ChordAccomp = tech == ProcTechnique.Serial && res.PitchRow != null
                ? SerialVerticalization(res.PitchRow, total, barSlices, tonicPc)
                : BuildDiatonicAccomp(res.Melody, bars, barSlices, tonicPc, scale);
            return res;
        }

        static void Assemble(ProcResult res, List<int> rhythm, List<int> pitches)
        {
            if (pitches == null || pitches.Count == 0) return;
            int pos = 0;
            for (int i = 0; i < rhythm.Count; i++)
            {
                int dur = rhythm[i], p = pitches[i % pitches.Count];
                if (p != REST) res.Melody.Add(new RiffNote(p - 12, pos, dur));
                pos += dur;
            }
        }

        // ============================================================= 1. SERIALISM (pitch row; rhythm from the shared layer)
        static List<int> SerialPitches(ProcResult res, int count, int tonicPc, Random rng, int lo, int hi)
        {
            var row = Shuffle(Enumerable.Range(0, 12).ToArray(), rng);
            res.PitchRow = row;
            var pitches = new List<int>(count + 12);
            int prev = (lo + hi) / 2, k = 0, guard = 0;
            while (pitches.Count < count && guard++ < 100000)
            {
                foreach (int pc in ApplyRowForm(row, k, tonicPc))
                {
                    int pitch = PlaceNear(prev, pc, lo, hi);
                    pitches.Add(pitch); prev = pitch;
                    if (pitches.Count >= count) break;
                }
                k++;
            }
            return pitches;
        }

        static int[] ApplyRowForm(int[] row, int k, int tonicPc)
        {
            int n = row.Length, form = k & 3, tn = (k * 5) % 12;         // 0=P 1=I 2=R 3=RI, rotating T
            var outp = new int[n];
            for (int i = 0; i < n; i++)
            {
                int v = row[i];
                if (form == 1 || form == 3) v = Mod(2 * row[0] - v, 12);  // inversion around the first note
                outp[i] = Mod(v + tn + tonicPc, 12);
            }
            if (form == 2 || form == 3) Array.Reverse(outp);              // retrograde
            return outp;
        }

        static List<RiffNote> SerialVerticalization(int[] row, int total, int barSlices, int tonicPc)
        {
            var outl = new List<RiffNote>();
            int bars = Math.Max(1, total / barSlices);
            for (int b = 0; b < bars; b++)
            {
                int baseIdx = (b * 3) % 12, prev = 48;
                for (int j = 0; j < 3; j++)
                {
                    int pc = Mod(row[(baseIdx + j) % 12] + tonicPc, 12);
                    int pitch = PlaceNear(prev, pc, 44, 64);
                    if (pitch <= prev) pitch += 12;
                    while (pitch > 67) pitch -= 12;
                    outl.Add(new RiffNote(pitch - 12, b * barSlices, barSlices));
                    prev = pitch;
                }
            }
            return outl;
        }

        // ============================================================= 2. CELLULAR AUTOMATON (elementary K2R1, Beyls readout)
        static List<int> CaPitches(int count, int tonicPc, int[] scale, bool chromatic, Random rng, int lo, int hi)
        {
            const int W = 25;
            int[] ruleChoices = { 90, 110, 30, 150, 54 };
            int rule = ruleChoices[rng.Next(ruleChoices.Length)];
            var row = new bool[W];
            for (int i = 0; i < W; i++) row[i] = rng.NextDouble() < 0.35;   // Langton λ ≈ 35 %
            row[W / 2] = true;
            int read = W / 2;
            var pitches = new List<int>(count);
            int prev = (lo + hi) / 2, guard = 0;
            while (pitches.Count < count && guard++ < 100000)
            {
                int nb = 0;
                for (int d = -2; d <= 2; d++) nb = (nb << 1) | (row[Mod(read + d, W)] ? 1 : 0);
                if (nb == 0) pitches.Add(REST);
                else
                {
                    int pitch = chromatic ? PlaceNear(prev, Mod(tonicPc + nb, 12), lo, hi)
                                          : PitchFromDegree(nb % (2 * scale.Length), tonicPc, scale, prev, lo, hi);
                    pitches.Add(pitch); prev = pitch;
                }
                row = StepCA(row, rule);
            }
            return pitches;
        }

        static bool[] StepCA(bool[] row, int rule)
        {
            int W = row.Length; var next = new bool[W];
            for (int i = 0; i < W; i++)
            {
                int cfg = (row[Mod(i - 1, W)] ? 4 : 0) | (row[i] ? 2 : 0) | (row[Mod(i + 1, W)] ? 1 : 0);
                next[i] = ((rule >> cfg) & 1) != 0;
            }
            return next;
        }

        // ============================================================= 3. L-SYSTEM (Lindenmayer / DuBois relative mapping)
        static List<int> LSystemPitches(int tonicPc, int[] scale, Random rng, int lo, int hi)
        {
            var sets = new List<(string axiom, Dictionary<char, string> rules, int depth)>
            {
                ("X", new Dictionary<char,string>{ {'X',"F-[[X]+X]+F[+FX]-X"}, {'F',"FF"} }, 4),
                ("F", new Dictionary<char,string>{ {'F',"F+F--F+F"} }, 3),
                ("A", new Dictionary<char,string>{ {'A',"AB+"}, {'B',"A-"} }, 6),
            };
            var set = sets[rng.Next(sets.Count)];
            string s = Rewrite(set.axiom, set.rules, set.depth);

            var pitches = new List<int>();
            int deg = 3, prev = (lo + hi) / 2;
            var stack = new Stack<int>();
            foreach (char ch in s)
            {
                switch (ch)
                {
                    case 'F': case 'A': case 'B':
                        int pitch = PitchFromDegree(deg, tonicPc, scale, prev, lo, hi);
                        pitches.Add(pitch); prev = pitch; break;
                    case '+': deg++; break;
                    case '-': deg--; break;
                    case '[': stack.Push(deg); break;
                    case ']': if (stack.Count > 0) deg = stack.Pop(); break;
                }
            }
            if (pitches.Count == 0) pitches.Add((lo + hi) / 2);
            return pitches;
        }

        static string Rewrite(string s, Dictionary<char, string> rules, int depth)
        {
            for (int d = 0; d < depth; d++)
            {
                var sb = new System.Text.StringBuilder(s.Length * 2);
                foreach (char c in s) sb.Append(rules.TryGetValue(c, out var r) ? r : c.ToString());
                s = sb.ToString();
                if (s.Length > 20000) break;
            }
            return s;
        }

        // ============================================================= 4. GENETIC (Towsey objective fitness = the "critic")
        static List<int> GeneticPitches(int count, int tonicPc, int[] scale, Random rng, int lo, int hi,
            List<(int rootPc, int quality)> harmony, List<int> rhythm, int barSlices)
        {
            const int pop = 40, gens = 60; const double mutRate = 0.12;
            Func<int[]> randGenome = () =>
            {
                var g = new int[count];
                for (int i = 0; i < count; i++) g[i] = rng.NextDouble() < 0.125 ? -1 : rng.Next(0, 2 * scale.Length); // rest 12.5 %
                return g;
            };
            var population = new List<int[]>();
            for (int i = 0; i < pop; i++) population.Add(randGenome());

            int[] best = population[0]; double bestF = double.NegativeInfinity;
            for (int gen = 0; gen < gens; gen++)
            {
                var scored = population.Select(g => (g, f: PitchFitness(g, tonicPc, scale, lo, hi, harmony, rhythm, barSlices))).ToList();
                foreach (var s in scored) if (s.f > bestF) { bestF = s.f; best = s.g; }
                double sum = scored.Sum(s => Math.Max(0.0001, s.f));
                var next = new List<int[]>();
                while (next.Count < pop)
                {
                    var a = Roulette(scored, sum, rng); var b = Roulette(scored, sum, rng);
                    var child = new int[count]; int cut = rng.Next(count);
                    for (int i = 0; i < count; i++) child[i] = i < cut ? a[i] : b[i];
                    for (int i = 0; i < count; i++) if (rng.NextDouble() < mutRate) child[i] = rng.NextDouble() < 0.125 ? -1 : rng.Next(0, 2 * scale.Length);
                    next.Add(child);
                }
                population = next;
            }
            return DecodeDegrees(best, tonicPc, scale, lo, hi);
        }

        static List<int> DecodeDegrees(int[] g, int tonicPc, int[] scale, int lo, int hi)
        {
            var pitches = new List<int>(g.Length); int prev = (lo + hi) / 2;
            foreach (int d in g)
            {
                if (d < 0) { pitches.Add(REST); continue; }
                int pitch = PitchFromDegree(d, tonicPc, scale, prev, lo, hi);
                pitches.Add(pitch); prev = pitch;
            }
            return pitches;
        }

        // Towsey PITCH features toward their corpus means (rhythm is meter-fixed externally, so only pitch is scored).
        static double PitchFitness(int[] g, int tonicPc, int[] scale, int lo, int hi,
            List<(int rootPc, int quality)> harmony, List<int> rhythm, int barSlices)
        {
            var decoded = DecodeDegrees(g, tonicPc, scale, lo, hi);
            var pitches = decoded.Where(p => p != REST).ToList();
            if (pitches.Count < 3) return 0;
            var intervals = new List<int>();
            for (int i = 1; i < pitches.Count; i++) intervals.Add(pitches[i] - pitches[i - 1]);
            int nIv = intervals.Count;

            double pitchVariety = pitches.Distinct().Count() / (double)pitches.Count;
            double disson = nIv == 0 ? 0 : intervals.Average(iv => Dissonance(Math.Abs(iv)));
            double rising = nIv == 0 ? 0 : intervals.Count(iv => iv > 0) / (double)nIv;
            int sameDir = 0; for (int i = 1; i < nIv; i++) if (intervals[i] != 0 && Math.Sign(intervals[i]) == Math.Sign(intervals[i - 1])) sameDir++;
            double stability = nIv <= 1 ? 0 : sameDir / (double)(nIv - 1);

            double f = (1 - Math.Abs(pitchVariety - 0.27)) + (1 - Math.Abs(disson - 0.01))
                     + (1 - Math.Abs(rising - 0.49)) + (1 - Math.Abs(stability - 0.40));

            if (harmony != null && harmony.Count > 0 && rhythm != null)   // Papadopoulos: reward chord tones
            {
                int pos = 0, onChord = 0, tot = 0;
                for (int i = 0; i < g.Length && i < rhythm.Count; i++)
                {
                    if (decoded[i] != REST)
                    {
                        int bar = Math.Min(harmony.Count - 1, pos / Math.Max(1, barSlices));
                        if (IsChordTone(decoded[i], harmony[bar])) onChord++;
                        tot++;
                    }
                    pos += rhythm[i];
                }
                if (tot > 0) f += onChord / (double)tot;
            }
            return f;
        }

        static double Dissonance(int semis)
        {
            int iv = semis == 13 ? 13 : semis % 12;
            if (iv == 6 || iv == 11 || iv == 13) return 1.0;
            if (iv == 10) return 0.5;
            return 0.0; // 0,1,2,3,4,5,7,8,9,12
        }

        static int[] Roulette(List<(int[] g, double f)> scored, double sum, Random rng)
        {
            double r = rng.NextDouble() * sum, acc = 0;
            foreach (var s in scored) { acc += Math.Max(0.0001, s.f); if (acc >= r) return s.g; }
            return scored[scored.Count - 1].g;
        }

        // ============================================================= 5. FRACTAL 1/f (pink noise, Voss-McCartney)
        static List<int> FractalPitches(int count, int tonicPc, int[] scale, Random rng, int lo, int hi)
        {
            var gen = new VossMcCartney(6, rng);
            var pitches = new List<int>(count); int prev = (lo + hi) / 2;
            for (int n = 0; n < count; n++)
            {
                int degIdx = (int)Math.Round(gen.Next(n) * (2 * scale.Length - 1));
                int pitch = PitchFromDegree(degIdx, tonicPc, scale, prev, lo, hi);
                pitches.Add(pitch); prev = pitch;
            }
            return pitches;
        }

        sealed class VossMcCartney
        {
            readonly double[] src; readonly Random rng; int prevN = -1;
            public VossMcCartney(int n, Random r) { src = new double[n]; rng = r; for (int i = 0; i < n; i++) src[i] = rng.NextDouble(); }
            public double Next(int n)
            {
                if (prevN >= 0) { int diff = prevN ^ n; for (int b = 0; b < src.Length; b++) if (((diff >> b) & 1) != 0) src[b] = rng.NextDouble(); }
                prevN = n; return src.Average();
            }
        }

        // ============================================================= 6. THUE-MORSE (self-similar morphism)
        static List<int> ThueMorsePitches(int count, int tonicPc, int[] scale, Random rng, int lo, int hi)
        {
            int deg = 2 + rng.Next(0, 5), up = 1 + rng.Next(0, 2), off = rng.Next(0, 8);
            var pitches = new List<int>(count); int prev = (lo + hi) / 2;
            for (int n = 0; n < count; n++)
            {
                deg += ThueMorseBit(n + off) == 0 ? up : -up;
                int pitch = PitchFromDegree(deg, tonicPc, scale, prev, lo, hi);
                pitches.Add(pitch); prev = pitch;
            }
            return pitches;
        }

        static int ThueMorseBit(int n) { int c = 0; while (n > 0) { c ^= (n & 1); n >>= 1; } return c; }

        // ============================================================= shared helpers
        static int Mod(int a, int m) { int r = a % m; return r < 0 ? r + m : r; }

        static int[] Shuffle(int[] a, Random rng)
        {
            for (int i = a.Length - 1; i > 0; i--) { int j = rng.Next(i + 1); int t = a[i]; a[i] = a[j]; a[j] = t; }
            return a;
        }

        static int PitchFromDegree(int degIdx, int tonicPc, int[] scale, int prev, int lo, int hi)
        {
            int n = scale.Length, oct = (int)Math.Floor(degIdx / (double)n);
            int pitch = tonicPc + 60 + scale[Mod(degIdx, n)] + 12 * oct;
            while (pitch - prev > 7 && pitch - 12 >= lo) pitch -= 12;
            while (prev - pitch > 7 && pitch + 12 <= hi) pitch += 12;
            while (pitch < lo) pitch += 12;
            while (pitch > hi) pitch -= 12;
            return pitch;
        }

        static int PlaceNear(int prev, int pc, int lo, int hi)
        {
            int basePitch = prev - Mod(prev, 12) + Mod(pc, 12);
            int best = basePitch, bestD = Math.Abs(basePitch - prev);
            foreach (int cand in new[] { basePitch - 12, basePitch + 12 })
                if (Math.Abs(cand - prev) < bestD) { bestD = Math.Abs(cand - prev); best = cand; }
            while (best < lo) best += 12;
            while (best > hi) best -= 12;
            return best;
        }

        static bool IsChordTone(int pitch, (int rootPc, int quality) chord)
        {
            int pc = Mod(pitch, 12), root = Mod(chord.rootPc, 12);
            return pc == root || pc == Mod(root + 3, 12) || pc == Mod(root + 4, 12) || pc == Mod(root + 7, 12);
        }

        /// <summary>Public: a per-bar diatonic block-chord accompaniment derived from a melody (used to give a
        /// standalone theme/variation its chords when no chord track exists).</summary>
        public static List<RiffNote> DiatonicAccompaniment(List<RiffNote> melody, int bars, int barSlices, int tonicPc, int[] scale)
            => BuildDiatonicAccomp(melody ?? new List<RiffNote>(), Math.Max(1, bars), Math.Max(Beat, barSlices),
                                   Mod(tonicPc, 12), (scale == null || scale.Length == 0) ? new[] { 0, 2, 4, 5, 7, 9, 11 } : scale);

        static List<RiffNote> BuildDiatonicAccomp(List<RiffNote> mel, int bars, int barSlices, int tonicPc, int[] scale)
        {
            var outl = new List<RiffNote>();
            for (int b = 0; b < bars; b++)
            {
                int bs = b * barSlices, be = bs + barSlices;
                RiffNote? head = null;
                foreach (var n in mel) if (n.Start >= bs && n.Start < be) { head = n; break; }
                int rootPc = head.HasValue ? Mod(head.Value.Note + 12 - tonicPc, 12) : 0;
                int di = NearestDegreeIndex(rootPc, scale), prev = 48;
                for (int j = 0; j < 3; j++)
                {
                    int pitch = PitchFromDegree(di + 2 * j, tonicPc, scale, prev, 40, 64);
                    if (pitch <= prev && j > 0) pitch += 12;
                    outl.Add(new RiffNote(pitch - 12, bs, barSlices));
                    prev = pitch;
                }
            }
            return outl;
        }

        static int NearestDegreeIndex(int pc, int[] scale)
        {
            int best = 0, bestD = 99;
            for (int i = 0; i < scale.Length; i++) { int d = Math.Min(Mod(pc - scale[i], 12), Mod(scale[i] - pc, 12)); if (d < bestD) { bestD = d; best = i; } }
            return best;
        }
    }
}
